WIP: Implementing Calldata Decoding to JSC Types
seanjameshan/starknet.js pull request #1018
Opened 2024-03-15 13:03 UTC by AryanGodara

## Motivation and Resolution

...

### RPC version (if applicable)

...

## Usage related changes

- Change 1.
- ...

## Development related changes

- Change 1.
- ...

## Checklist:

- [ ] Performed a self-review of the code
- [ ] Rebased to the last commit of the target branch (or merged it into my branch)
- [ ] Linked the issues which this PR resolves
- [ ] Documented the changes in code (API docs will be generated automatically)
- [ ] Updated the tests
- [ ] All tests are passing

2024-03-15 19:46 UTC, AryanGodara commented
@tabaktoni  @ivpavici 
I've tried to implement one-half of the issue and could really use your review on this one (no rush though, ik the weekend has started 😅)

2024-03-18 08:54 UTC, tabaktoni commented
Good point splitting it into two subtasks is more manageable.
Will deal with it this week.

2024-03-20 10:00 UTC, AryanGodara commented
> Good point splitting it into two subtasks is more manageable. Will deal with it this week.

Are the current changes a step in the right direction? If so, then I'll start to work on the API encoder part as well :D

2024-03-21 15:16 UTC, ivpavici requested changes

2024-03-21 15:16 UTC, ivpavici commented on src/utils/cairoDataTypes/uint256.ts
> +    if (calldata.length !== 2) {
maybe `import assert from '../assert';` to check this?

2024-03-21 15:16 UTC, ivpavici commented on src/utils/calldata/apiDataEncoder.ts
maybe to put some TODO for now, or add the whole file later?

2024-03-21 15:16 UTC, ivpavici commented on src/utils/calldata/calldataDecoder.ts
> +import { byteArrayFromString } from './byteArray';
please fix these github actions errors 🙏

2024-03-22 14:17 UTC, tabaktoni commented
In general, this is a good direction.
We need to have encoding < - > decoding tests for this.
So take some call data encode it and then decode, you should get back the initial objects sent to the calldata.

I think you would focus for now only on this part of the task as there are multiple data types to support this flow.
Some of them are extracted to singular classes like uin256 and decoding call data will be part of the class, but at the moment it is not so important as we can do it in future steps.

Priority is to have test type by type and mix types for this flow.

2024-03-26 10:37 UTC, AryanGodara commented
> In general, this is a good direction. We need to have encoding < - > decoding tests for this. So take some call data encode it and then decode, you should get back the initial objects sent to the calldata.
> 
> I think you would focus for now only on this part of the task as there are multiple data types to support this flow. Some of them are extracted to singular classes like uin256 and decoding call data will be part of the class, but at the moment it is not so important as we can do it in future steps.
> 
> Priority is to have test type by type and mix types for this flow.

Hi, sorry I was busy last week and couldn't get to this task, I'll quickly get to addressing these, and implementing the rest of the solution :)

2024-03-26 12:34 UTC, AryanGodara commented
@tabaktoni I've written an initial test. Does this approach seem correct to you?
If so, I'll begin to write more testcases
https://github.com/starknet-io/starknet.js/blob/745eb9a801e49b71e14dc87fba66ed709acf58fc/__tests__/utils/calldataDecode.test.ts#L8

2024-04-23 14:30 UTC, tabaktoni commented
Not sure what was the goal with Iterator, but in general I imagine test to be like:

```ts
import contractX....

const data = {
	list: [1, 3n], 
	balance: "0x34"
};

const cd = new CallData(contractX.abi);
const compoledCalldata = cd.compile(testData)
const decompiledCalldata = cd.decompile(compoledCalldata)

expect(data).toEqual(decompiledCalldata)
```

You can use any of predefined contracts abi we already have in __mocks__ for example:
https://github.com/starknet-io/starknet.js/blob/dceaf85f38273d0497156526e227ee98af988618/__tests__/cairo1v2.test.ts#L560 this can be data
and use 
```ts
const contractCallData: CallData = new CallData(compiledComplexSierra.abi);
```

2024-04-26 14:53 UTC, PhilippeR26 commented
I am a bit in trouble to review this PR.
My DAPP for encoding/decoding is using Starknet.js v6.8.0, and do not needs new functionality. So external tools have already all what is necessary to encode/decode calldata and custom types.
Is the purpose of this PR to have something more user friendly?

2024-04-27 19:28 UTC, AryanGodara commented
> I am a bit in trouble to review this PR. My DAPP for encoding/decoding is using Starknet.js v6.8.0, and do not needs any new functionality. So external tools have already all what is necessary to encode/decode calldata and custom types. Is the purpose of this PR to have something more user friendly?
> 
> For example, if I want to decode the encoded parameters of a function, I just write 4 lines :
> 
> ```ts
> const encodedCalldata=["4674576345645645","2000","0"];
> const fnName="transfer";
> 
> const myCallData=new CallData(abi);
> const { inputs } = myCallData.parser.getLegacyFormat().find((abiItem:AbiEntry) => abiItem.name === fnName) as FunctionAbi;
> const inputsTypes=inputs.map((inp:any)=>{return inp.type as string});
> const result=myCallData.decodeParameters(inputsTypes,encodedCalldata);
> console.log(result);
> ```

Hey, @PhilippeR26, Can you share a link for this code? I'd love to take a look as well.

As for the PR, from the issue, according to me, while you already have a great way to accomplish this, having a proper functionality setup within the repo itself would be both more user-friendly and also more sustainable. This will allow a seamless transition between the blockchain and JSC types without having to rely on external tools/write custom logic yourself for each new use case.
 
Plus, it improves flexibility and customization for handling complex data structures. Additionally, it'll help in validation, error handling, and testing, enhancing the reliability and maintainability of the repo.

2024-04-27 20:29 UTC, PhilippeR26 commented
https://github.com/PhilippeR26/starknet-encode-decode/blob/046970f58ff07ceb0cf852d4f1cf8638eee7db70/src/app/components/client/EncodeDecode/DecodeFunctionCalldata.tsx#L76-L78

Encoding of a custom type is working but isn't user friendly. It should be improved, to be as nice as `decodeParameters`.
![image](https://github.com/starknet-io/starknet.js/assets/81040730/dc116a91-3941-449a-b405-416352cb2dee)

2024-04-27 22:38 UTC, AryanGodara commented
> https://github.com/PhilippeR26/starknet-encode-decode/blob/046970f58ff07ceb0cf852d4f1cf8638eee7db70/src/app/components/client/EncodeDecode/DecodeFunctionCalldata.tsx#L76-L78
> 
> Encoding of a custom type is working but isn't user friendly. It should be improved, to be as nice as `decodeParameters`. ![image](https://private-user-images.githubusercontent.com/81040730/326211332-dc116a91-3941-449a-b405-416352cb2dee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNTAwOTgsIm5iZiI6MTcxNDI0OTc5OCwicGF0aCI6Ii84MTA0MDczMC8zMjYyMTEzMzItZGMxMTZhOTEtMzk0MS00NDlhLWI0MDUtNDE2MzUyY2IyZGVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDIwMjk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1YmIwYzIwOGFiMDdhY2M3NzkwMzQwMjU0NWYzOTE1MTMwOGY3ZTg5M2Y4NDQ0ZWU0ZDNmOWZiOTRhODg0NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SyBHZbjPZoYwQqiw_0kULPiWlCo8irg-WCVSzOsJKn0)

Thanks for this!
I'm working on improving the structure of the code I wrote above. It wasn't compatible with the existing format; so I'm rewriting it. 

The PR isn't quite read for review at the moment, making lots of breaking changes, and I'll later squash all the temp commits into a final one.
So please feel free to `not review` for some time 😅

2024-04-30 12:58 UTC, PhilippeR26 commented
And if you want to encode a function response, you can use the current code this way :
```typescript
const params = [cairo.tuple(300,new CairoOption<BigNumberish>(CairoOptionVariant.Some,50));]; 
const selectedType = "(core::felt252, core::option::Option::<core::integer::u8>)"; 
const iter = params[Symbol.iterator](); 
const structs = CallData.getAbiStruct(abi);
const enums = CallData.getAbiEnum(abi);
const abiExtract = abi.find((abiItem) => abiItem.name === selectedType); 
const inputAbi: AbiEntry = abiExtract ? 
    { name: abiExtract.type, type: abiExtract.name } :
    { name: "literal", type: responseType };
const result = parseCalldataField(iter, inputAbi, structs, enums);
```

2024-05-03 07:52 UTC, tabaktoni requested changes
Some guidelines:
- The response is only an object no need for an array.
- Cleanup
- re-enable lint src/
- resolve circle dependency

2026-04-30 11:22 UTC, closed without merging

2026-04-30 11:22 UTC, tabaktoni commented
Clopsing in favor of #1496